import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Hydrate from "./components/Hydrate";
import { CartProvider } from "./context/CartContext"; // 👈 importe aqui

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Hydrate>
          <CartProvider> {/* ✅ envolve aqui */}
            <Navbar />
            <main className="bg-pink-100">{children}</main>
          </CartProvider>
        </Hydrate>
      </body>
    </html>
  );
}
